# -*- coding: utf-8 -*-
"""shadow fox .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwTQ6JOokHP_StjQ1n_5nUZ7TejVNUOg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns
df=pd.read_csv('delhiaqi.csv')
df

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("delhiaqi.csv")

df['date'] = pd.to_datetime(df['date'])

plt.figure()
plt.plot(df['date'], df['pm2_5'])
plt.title("Overall PM2.5 Trend in Delhi (as AQI proxy)")
plt.xlabel("Year")
plt.ylabel("PM2.5 Concentration")
plt.show()


pollutants = ['co', 'no', 'no2', 'o3', 'so2', 'pm2_5', 'pm10', 'nh3']

plt.figure()
df[pollutants].mean().plot(kind='bar')
plt.title("Average Pollutant Concentration")
plt.ylabel("Concentration Level")
plt.show()

plt.figure()
sns.heatmap(df[pollutants].corr(), annot=True)
plt.title("Correlation Between Pollutants")
plt.show()

def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8]:
        return "Monsoon"
    else:
        return "Post-Monsoon"

df['Season'] = df['date'].dt.month.apply(get_season)

plt.figure()
sns.boxplot(x='Season', y='pm2_5', data=df)
plt.title("Seasonal PM2.5 Variation in Delhi (as AQI proxy)")
plt.ylabel("PM2.5 Concentration")
plt.show()

df['Month'] = df['date'].dt.month

plt.figure()
sns.lineplot(x='Month', y='pm2_5', data=df)
plt.title("Monthly PM2.5 Pattern (as AQI proxy)")
plt.xlabel("Month")
plt.ylabel("PM2.5 Concentration")
plt.show()

plt.figure()
sns.lineplot(x='date', y='pm2_5', data=df, label='pm2_5')
sns.lineplot(x='date', y='pm10', data=df, label='pm10')
plt.title("Particulate Matter Trends (PM2.5 & PM10)")
plt.ylabel("Concentration")
plt.show()

print("Delhi AQI analysis for first 5 research sets completed successfully (using pm2_5 as AQI proxy).")